### ISSUE TITLE
CSS Framework

### ISSUE THREAD

**Issue by nnorman15** [nnorman15/proj1-group5#1]
# CSS Framework
## Content Requirements
* Foundation : https://get.foundation/templates.html
* Real Estate Template
* Strip out all content in the top gray bar except the ‘Interplanetary’ and replace ‘Interplanetary’ with name of project (TBD).

This is the starting point.  Will revise content and placement (swapping search from right to left, etc) as we go.
Branch : feature/layout

**Comment by nikuk1** [comment]
Completed styling up to presentation time Thursday July 16th 2020
