### ISSUE TITLE
Hiking Trail Results

### ISSUE THREAD

**Issue by nnorman15** [nnorman15/proj1-group5#6]
# Hiking Trail Results
## Content Requirements

* If records are found
 ** Results are in cards with image of hike (If provided)
 ** Show 6 results
 ** Load more button loads another set of 6
* Name of Trail - is link that opens modal
** Distance
** Difficulty
** Overview (capped at 255 chars or something) - if there is more content show ‘view more’ button or ellipses
** 'View More' button or ellipses is link that opens modal
* If no records found
** Show message that says something like, “No records match your search criteria, please try again.”
** POTENTIAL ENHANCEMENT IF THERE IS TIME : Could also show a list of random favorites or nearest top three favorite hikes to lead users to optional hikes.

Branch : feature/hikes

**Comment by cullinans1** [comment]
Results are shown on page with image, if no image provided then stock image is in place.

**Comment by cullinans1** [comment]
Load button functions properly
