### ISSUE TITLE
Modal

### ISSUE THREAD

**Issue by nnorman15** [nnorman15/proj1-group5#7]
# Modal
## Content Requirements
* Complete list of contents TBD but would include things like distance, elevation, overview.
* Once we get a good feel for the contents in the api will discuss with team and finalize list.

Branch : feature/modal

**Comment by Cassiecatt** [comment]
Completed, just need to decide if we want to add additional information into the modal and if we want to add more styling

**Comment by Cassiecatt** [comment]
Functionality is completed. We can discuss styling if needed
